# Generated by Django 2.2.7 on 2019-11-10 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.PositiveSmallIntegerField()),
                ('category_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ChartNoteItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ChartSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_code', models.PositiveIntegerField()),
                ('sub_category_name', models.CharField(max_length=256)),
                ('notes', models.PositiveIntegerField(default=0)),
                ('category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartsetup.ChartCategory')),
            ],
        ),
        migrations.CreateModel(
            name='GJournalMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date/Time')),
                ('ref_number', models.PositiveIntegerField(default=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('total_debit', models.FloatField(default=0)),
                ('total_credit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SetupInventoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_category_code', models.PositiveSmallIntegerField(blank=True)),
                ('inventory_category_name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetupVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/profilepix/')),
                ('signature', models.ImageField(blank=True, upload_to='images/signature/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetupInventoryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(blank=True, default='', max_length=256)),
                ('inventory_name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('inventory_category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartsetup.SetupInventoryCategory', verbose_name='Inventory Category')),
            ],
        ),
        migrations.CreateModel(
            name='SetupClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True, default='')),
                ('phone', models.CharField(default='', max_length=100)),
                ('account_officer', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Receipt Date/Time')),
                ('receipt_number', models.PositiveIntegerField(default=100)),
                ('bill_to', models.CharField(blank=True, default='', max_length=256, verbose_name='Received from')),
                ('description', models.TextField(default='')),
                ('pay_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('transfer', 'Transfer'), ('draft', 'Draft')], default='Cheque', max_length=50)),
                ('total_amount', models.FloatField(default=0)),
                ('Debit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems')),
                ('cash_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Cash Account')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupClients', verbose_name='Client Name')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=256)),
                ('unit_price', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('credit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems')),
                ('receipt_main_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartsetup.ReceiptMain')),
                ('revenue_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Revenue Account')),
            ],
        ),
        migrations.CreateModel(
            name='GJournalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=256)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory')),
                ('journal_main_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartsetup.GJournalMain')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Expense Date/Time')),
                ('voucher_number', models.PositiveIntegerField(default=100)),
                ('payee', models.CharField(blank=True, default='', max_length=256, verbose_name='Payee')),
                ('description', models.TextField(default='')),
                ('pay_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('transfer', 'Transfer'), ('draft', 'Draft')], default='Cheque', max_length=50)),
                ('total_amount', models.FloatField(default=0)),
                ('cash_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Cash Account')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=256)),
                ('unit_price', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('expense_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Revenue Account')),
                ('expense_main_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartsetup.ExpenseMain')),
            ],
        ),
        migrations.AddField(
            model_name='chartnoteitems',
            name='sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='noteitems', to='smartsetup.ChartSubCategory'),
        ),
    ]
