# Generated by Django 2.2.7 on 2019-11-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0002_auto_20191111_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type', models.CharField(blank=True, default='', max_length=256)),
                ('account_id', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('ref_number', models.PositiveIntegerField(default='')),
                ('description', models.CharField(default='', max_length=256)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
            ],
        ),
    ]
