# Generated by Django 2.2.7 on 2019-11-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0003_generalledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems'),
        ),
    ]
