# Generated by Django 2.2.7 on 2019-11-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0004_auto_20191113_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='sub_Trans',
            field=models.BooleanField(default=0),
        ),
    ]
