# Generated by Django 2.2.7 on 2019-11-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0006_auto_20191124_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalledger',
            options={'ordering': ['-credit']},
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='smartsetup.ChartNoteItems'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='smartsetup.ChartSubCategory'),
        ),
    ]
