# Generated by Django 2.2.7 on 2019-11-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartsetup', '0008_auto_20191125_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupclients',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(default='', max_length=100)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Prof', 'Prof'), ('Chief', 'Chief'), ('Sir', 'Sir'), ('Pr', 'Pr'), ('Imam', 'Imam'), ('Elder', 'Elder')], default='Mr', max_length=50)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('nick_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=50)),
                ('birthdate', models.DateTimeField(auto_now=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('hire_date', models.DateTimeField(auto_now=True)),
                ('division', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.CharField(blank=True, default='', max_length=200)),
                ('login_profile', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
