# Generated by Django 2.2.7 on 2019-11-28 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0009_auto_20191127_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='login_profile',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensemain',
            name='payee',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.EmployeeProfile'),
        ),
    ]
