# Generated by Django 2.2.7 on 2019-11-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0010_auto_20191128_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemain',
            name='credit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems'),
        ),
    ]
