# Generated by Django 2.2.7 on 2019-11-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0011_expensemain_credit_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetails',
            name='Debit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems'),
        ),
        migrations.AlterField(
            model_name='expensedetails',
            name='expense_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory', verbose_name='Expense Category'),
        ),
    ]
