# Generated by Django 2.2.7 on 2019-12-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0013_auto_20191201_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ref_number', models.PositiveIntegerField(default='')),
                ('description', models.CharField(default='', max_length=256)),
                ('total_debit', models.FloatField(default=0)),
                ('total_credit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralJournalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=256)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems')),
                ('journal_main', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartsetup.GeneralJournal')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory')),
            ],
        ),
    ]
