# Generated by Django 2.2.7 on 2019-12-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0014_generaljournal_generaljournaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaljournaldetails',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='generaljournaldetails',
            name='journal_main',
        ),
        migrations.RemoveField(
            model_name='generaljournaldetails',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='gjournaldetails',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory'),
        ),
        migrations.AlterField(
            model_name='gjournaldetails',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems'),
        ),
        migrations.DeleteModel(
            name='GeneralJournal',
        ),
        migrations.DeleteModel(
            name='GeneralJournalDetails',
        ),
    ]
