# Generated by Django 2.2.7 on 2019-12-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0015_auto_20191201_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartnoteitems',
            options={'ordering': ['-item_name']},
        ),
        migrations.AlterModelOptions(
            name='chartsubcategory',
            options={'ordering': ['sub_category_name']},
        ),
    ]
