# Generated by Django 2.2.7 on 2019-12-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0016_auto_20191201_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartCategory'),
        ),
    ]
