# Generated by Django 2.2.7 on 2019-12-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0019_purchasedetails_purchasemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='inventory_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupInventoryItems'),
        ),
    ]
