# Generated by Django 3.0 on 2019-12-23 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0020_purchasedetails_inventory_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date/Time')),
                ('ref_number', models.PositiveIntegerField(default=100)),
                ('inventory_code', models.CharField(max_length=256)),
                ('inventory_name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('store', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SetupDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetupFixedAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('acquisition_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupDepartment')),
            ],
        ),
    ]
