# Generated by Django 3.0 on 2019-12-23 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0021_inventoryjournal_setupdepartment_setupfixedassets'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupfixedassets',
            name='asset_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems'),
        ),
    ]
