# Generated by Django 3.0 on 2019-12-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0025_auto_20191223_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupfixedassets',
            name='others',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
