# Generated by Django 3.0 on 2019-12-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0027_auto_20191227_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupfixedassets',
            name='serial_no',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='setupfixedassets',
            name='depreciation_method',
            field=models.CharField(choices=[('Straight-line', 'Straight-line'), ('Double declining balance', 'Double declining balance'), ('Sum of years', 'Sum of years'), ('Units of production', 'Units of production')], default='Straight-line', max_length=50),
        ),
    ]
