# Generated by Django 3.0 on 2019-12-30 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0028_auto_20191230_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupfixedassets',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='setupfixedassets',
            name='purchase_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='setupfixedassets',
            name='salvage_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='setupfixedassets',
            name='useful_life',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
