# Generated by Django 3.0 on 2020-01-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0030_companyregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyregistration',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='companyregistration',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='companyregistration',
            old_name='Phone',
            new_name='phone',
        ),
    ]
