# Generated by Django 3.0 on 2020-01-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0031_auto_20200104_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupBegBalanceMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodno', models.PositiveIntegerField(default=0)),
                ('begindate', models.DateTimeField(auto_now=True)),
                ('enddate', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SetupBegbalanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(default='', max_length=256)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartNoteItems')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartCategory')),
                ('mainid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartsetup.SetupBegBalanceMain')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory')),
            ],
        ),
    ]
