# Generated by Django 3.0 on 2020-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0032_setupbegbalancedetails_setupbegbalancemain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setupbegbalancemain',
            old_name='begindate',
            new_name='entrydate',
        ),
        migrations.RenameField(
            model_name='setupbegbalancemain',
            old_name='enddate',
            new_name='periodend',
        ),
        migrations.AddField(
            model_name='setupbegbalancemain',
            name='periodstart',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
