# Generated by Django 3.0 on 2020-01-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0035_auto_20200109_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='birthdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='hire_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='setupbegbalancemain',
            name='entrydate',
            field=models.DateField(),
        ),
    ]
