# Generated by Django 3.0 on 2020-01-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0038_auto_20200126_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='asset',
            field=models.BooleanField(default=False),
        ),
    ]
