# Generated by Django 3.0 on 2020-02-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0041_auto_20200226_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupDivision')),
            ],
        ),
    ]
