# Generated by Django 3.0 on 2020-03-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0042_setupunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupfixedassets',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
