# Generated by Django 3.0 on 2020-03-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0044_auto_20200310_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupvendors',
            name='vendor_type',
            field=models.CharField(choices=[('Agency', 'Agency'), ('Supplier', 'Supplier'), ('contractor', 'contractor')], default='Supplier', max_length=200),
        ),
    ]
