# Generated by Django 3.0 on 2020-03-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0045_auto_20200310_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupvendors',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='setupvendors',
            name='payer_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='setupvendors',
            name='tin_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='setupvendors',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
