# Generated by Django 3.0 on 2020-03-12 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartsetup', '0046_auto_20200311_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='unit',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupUnit'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupDepartment'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='division',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupDivision'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='login_profile',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
