# Generated by Django 3.0 on 2020-03-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0048_budgetdepartment_budgetdetails_budgetmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetails',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='budgetdetails',
            name='budget_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.ChartSubCategory'),
        ),
    ]
