# Generated by Django 3.0 on 2020-03-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0049_auto_20200322_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdetails',
            name='budget_type',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense')], default='', max_length=256),
        ),
    ]
