# Generated by Django 3.0 on 2020-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0051_expensedetails_budget_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupdivision',
            name='division_name',
            field=models.CharField(max_length=256, verbose_name='section'),
        ),
    ]
