# Generated by Django 3.0 on 2020-04-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0052_auto_20200331_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupunit',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupDivision', verbose_name='section'),
        ),
    ]
