# Generated by Django 3.0 on 2020-06-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0055_auto_20200528_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmain',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartsetup.SetupClients', verbose_name='Client Name'),
        ),
    ]
