# Generated by Django 3.0 on 2020-06-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0057_auto_20200624_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetmain',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetmain',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
