# Generated by Django 3.0 on 2020-07-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0058_auto_20200626_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdepartment',
            name='department_name',
            field=models.CharField(max_length=256),
        ),
    ]
