# Generated by Django 3.0 on 2020-07-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0059_auto_20200722_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensemain',
            options={'ordering': ['date']},
        ),
    ]
