# Generated by Django 3.0 on 2020-07-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0060_auto_20200726_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensemain',
            options={'ordering': ['-date']},
        ),
    ]
