# Generated by Django 3.0 on 2020-07-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsetup', '0062_setupinventorycategory_inventory_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemain',
            name='voucher_number2',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
